#include <stdio.h>

#include "gf65536.h"

int main(int argc, char** argv)
{
  gf65536_init_tables();

  /* Spew out the tables */
  int i;  
  fprintf(stdout, "\
/*\n\
 * This file is autogenerated by gfshare_maketable.\n\
 */\n\
\n\
static unsigned short gf65536_logs[65536] = {\n  ");
  for( i = 0; i < 65536; ++i ) {
    fprintf(stdout, "0x%04x", gf65536_logs[i]);
    if( i == 65535 )
      fprintf(stdout, "\n};\n");
    else if( (i % 8) == 7 )
      fprintf(stdout, ",\n  ");
    else
      fprintf(stdout, ", ");
  }
  
  /* The exp table we output from 0 to 131069 because that way when we
   * do the lagrange interpolation we don't have to be quite so strict
   * with staying inside the field which makes it quicker
   */
  
  fprintf(stdout, "\
\n\
static unsigned short gf65536_exps[131070] = {\n  ");
  for( i = 0; i < 131070; ++i ) {
    fprintf(stdout, "0x%04x", gf65536_exps[i]); /* gf65536_exps[65535]==gf65536_exps[0] */
    if( i == 131069 )
      fprintf(stdout, "\n};\n");
    else if( (i % 8) == 7)
      fprintf(stdout, ",\n  ");
    else
      fprintf(stdout, ", ");
  }
  
  return 0;
}

